/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "name": "Automatically add extensions",
  "description": "Auto-shows music, pen, and other extensions in the block category menu in the editor.",
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "settings": [
    {
      "name": "Music",
      "id": "music",
      "type": "boolean",
      "default": false
    },
    {
      "name": "Pen",
      "id": "pen",
      "type": "boolean",
      "default": false
    },
    {
      "name": "Text to Speech",
      "id": "text2speech",
      "type": "boolean",
      "default": false
    },
    {
      "name": "Translate",
      "id": "translate",
      "type": "boolean",
      "default": false
    },
      {
          "name": "Enable return",
          "id": "procedures_enable_return"
            "type": "boolean",
          "default": true
      }
  ],
  "dynamicDisable": true,
    "enabledByDefault": true,
  "tags": []
};
export default manifest;
